import { useEffect, useState } from 'react';
import type { CSSProperties } from 'react';
import { Chrome } from './components/Chrome';
import { DataFooter, EmptyMetric, PageHeading } from './components/Common';
import { ProviderLayers } from './components/ProviderLayers';
import { TextControls } from './components/TextControls';
import { corpusGateway } from './lib/gateway';
import { useNavigation } from './lib/navigation';
import { defaultPersonalData, defaultPreferences, toggleValue, usePersistentState } from './lib/persistence';
import type { PersonalData, ReaderPreferences } from './lib/persistence';
import type { BaniSummary, BaniView, CanonicalLine, ConcordancePage, ContributorSummary, CorpusInfo, CorpusSearchResponse, GlossaryResult, GroupedFrequency, ProviderCoverage, RaagContributorSummary, RaagSummary, RankedForm, RelatedForm, Screen, SearchMode, ShabadView, SourceWorkOption, TextUnitSummary, WordStats } from './types';

const emptySearch: CorpusSearchResponse = { query: '', mode: 'latin', results: [], candidateForms: [] };
const emptyConcordance: ConcordancePage = { total: 0, offset: 0, limit: 50, matches: [] };
type BrowseTab = 'banis' | 'contributors' | 'raags' | 'words';

export default function App() {
  const { screen, navigate, back } = useNavigation();
  const [query, setQuery] = useState('naam'); const [searchMode, setSearchMode] = useState<SearchMode>('auto');
  const [search, setSearch] = useState<CorpusSearchResponse>(emptySearch); const [sources, setSources] = useState<SourceWorkOption[]>([]);
  const [sourceWorkId, setSourceWorkId] = useState('source:G'); const [info, setInfo] = useState<CorpusInfo | null>(null);
  const [ang, setAng] = useState(1); const [angLines, setAngLines] = useState<CanonicalLine[]>([]); const [sabad, setSabad] = useState<ShabadView | null>(null);
  const [rankings, setRankings] = useState<RankedForm[]>([]); const [contributors, setContributors] = useState<ContributorSummary[]>([]);
  const [selectedContributor, setSelectedContributor] = useState<ContributorSummary | null>(null); const [contributorUnits, setContributorUnits] = useState<TextUnitSummary[]>([]);
  const [raags, setRaags] = useState<RaagSummary[]>([]); const [selectedRaag, setSelectedRaag] = useState<RaagSummary | null>(null);
  const [raagContributors, setRaagContributors] = useState<RaagContributorSummary[]>([]); const [raagContributor, setRaagContributor] = useState(''); const [raagUnits, setRaagUnits] = useState<TextUnitSummary[]>([]);
  const [banis, setBanis] = useState<BaniSummary[]>([]); const [bani, setBani] = useState<BaniView | null>(null);
  const [browseTab, setBrowseTab] = useState<BrowseTab>('banis'); const [browseFilter, setBrowseFilter] = useState('');
  const [selectedWord, setSelectedWord] = useState('ਹਰਿ'); const [wordStats, setWordStats] = useState<WordStats | null>(null);
  const [concordance, setConcordance] = useState<ConcordancePage>(emptyConcordance); const [relatedForms, setRelatedForms] = useState<RelatedForm[]>([]); const [grouped, setGrouped] = useState<GroupedFrequency | null>(null);
  const [glossary, setGlossary] = useState<GlossaryResult[]>([]); const [coverage, setCoverage] = useState<ProviderCoverage | null>(null);
  const [activeLine, setActiveLine] = useState<CanonicalLine | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [preferences, setPreferences] = usePersistentState('gurbani:preferences:v3', defaultPreferences);
  const [personal, setPersonal] = usePersistentState('gurbani:personal:v1', defaultPersonalData);
  const currentSource = sources.find(source => source.id === sourceWorkId);

  useEffect(() => { document.documentElement.dataset.theme = preferences.theme; }, [preferences.theme]);
  useEffect(() => { void loadSource('source:G', true); }, []);

  async function loadSource(source: string, first = false) {
    setBusy(true); setError(null);
    try {
      const [sourceInfo, sourceRows, lines, forms, people, raagRows, baniRows, providerCoverage] = await Promise.all([
        corpusGateway.corpusInfo(), corpusGateway.sources(), corpusGateway.getLines(1, source), corpusGateway.rankedForms(2000, source),
        corpusGateway.contributorSummaries(1000, source), corpusGateway.raagSummaries(source), corpusGateway.namedBanis(source), corpusGateway.providerCoverage()
      ]);
      setInfo(sourceInfo); setSources(sourceRows); setSourceWorkId(source); setAng(1); setAngLines(lines); setRankings(forms);
      setContributors(people); setRaags(raagRows); setBanis(baniRows); setCoverage(providerCoverage); setSearch(emptySearch);
      if (!first) navigate('home');
    } catch { setError('The installed reading data could not be opened. Remove the previous app build, then reinstall this one.'); }
    finally { setBusy(false); }
  }

  async function loadAng(value: number) { const next = Math.max(1, Math.min(currentSource?.maxAng ?? 1430, value)); setBusy(true); try { setAng(next); setAngLines(await corpusGateway.getLines(next, sourceWorkId)); navigate('read'); } catch { setError('That Ang could not be opened.'); } finally { setBusy(false); } }
  async function openSabad(id: string) { setBusy(true); try { const value = await corpusGateway.getTextUnit(id); setSabad(value); setPersonal(p => ({ ...p, readingPosition: value.id })); navigate('sabad'); } catch { setError('The complete Sabad could not be opened.'); } finally { setBusy(false); } }
  async function openBani(row: BaniSummary) { setBusy(true); try { setBani(await corpusGateway.getBani(row.id)); navigate('bani'); } catch { setError('This Bani could not be opened.'); } finally { setBusy(false); } }
  async function openContributor(row: ContributorSummary) { setBusy(true); setSelectedContributor(row); try { setContributorUnits(await corpusGateway.contributorUnits(row.id, sourceWorkId, 50, 0)); navigate('contributor'); } catch { setError('This contributor’s Sabads could not be opened.'); } finally { setBusy(false); } }
  async function moreContributor() { if (!selectedContributor) return; const rows = await corpusGateway.contributorUnits(selectedContributor.id, sourceWorkId, 50, contributorUnits.length); setContributorUnits(v => [...v, ...rows]); }
  async function openRaag(row: RaagSummary) { setBusy(true); setSelectedRaag(row); setRaagContributor(''); try { const [people, units] = await Promise.all([corpusGateway.raagContributorSummaries(row.name, sourceWorkId), corpusGateway.raagUnits(row.name, sourceWorkId, 50, 0)]); setRaagContributors(people); setRaagUnits(units); navigate('raag'); } catch { setError('This Raag could not be opened.'); } finally { setBusy(false); } }
  async function filterRaag(contributorId: string) { if (!selectedRaag) return; setRaagContributor(contributorId); setRaagUnits(await corpusGateway.raagUnits(selectedRaag.name, sourceWorkId, 50, 0, contributorId || undefined)); }
  async function moreRaag() { if (!selectedRaag) return; const rows = await corpusGateway.raagUnits(selectedRaag.name, sourceWorkId, 50, raagUnits.length, raagContributor || undefined); setRaagUnits(v => [...v, ...rows]); }
  async function runSearch() { setBusy(true); try { setSearch(await corpusGateway.searchCorpus(query, sourceWorkId, 80, searchMode)); navigate('search'); } catch { setSearch(emptySearch); setError('Search could not query the installed data.'); navigate('search'); } finally { setBusy(false); } }
  async function openWord(raw: string) { const word = cleanWord(raw); if (!word) return; setBusy(true); setSelectedWord(word); try { const [stats, page, related] = await Promise.all([corpusGateway.exactWordStats(word, sourceWorkId), corpusGateway.concordance(word, sourceWorkId, 50, 0), corpusGateway.relatedForms(word, sourceWorkId, 30)]); setWordStats(stats); setConcordance(page); setRelatedForms(related); setGrouped(null); navigate('word'); } catch { setError('No exact count has been inferred or substituted.'); } finally { setBusy(false); } }
  async function moreConcordance() { const page = await corpusGateway.concordance(selectedWord, sourceWorkId, 50, concordance.matches.length); setConcordance(v => ({ ...page, offset: 0, matches: [...v.matches, ...page.matches] })); }
  async function openGlossary(word: string) { setSelectedWord(cleanWord(word)); setGlossary(await corpusGateway.glossary(cleanWord(word), 40)); navigate('glossary'); }
  function showBrowse(tab: BrowseTab) { setBrowseTab(tab); setBrowseFilter(''); navigate('browse'); }

  const common = { preferences, setPreferences, personal, setPersonal, openSabad, openWord, setActiveLine };
  return <Chrome active={screen} onNavigate={navigate} onBack={back}><div className="screen" style={{ '--gurmukhi-color': preferences.gurmukhiColor, '--latin-color': preferences.latinColor } as CSSProperties}>
    {busy && <div className="busy">Opening…</div>}{error && <div className="error" role="alert">{error}<button onClick={() => setError(null)}>Dismiss</button></div>}
    <SourcePicker sources={sources} value={sourceWorkId} onChange={value => void loadSource(value)} />
    {screen === 'home' && <Home info={info} query={query} setQuery={setQuery} runSearch={runSearch} loadAng={loadAng} showBrowse={showBrowse} continueReading={() => personal.readingPosition ? void openSabad(personal.readingPosition) : void loadAng(ang)} />}
    {screen === 'read' && <AngReader ang={ang} maxAng={currentSource?.maxAng ?? 1430} lines={angLines} loadAng={loadAng} {...common} />}
    {screen === 'sabad' && sabad && <SabadReader sabad={sabad} {...common} />}
    {screen === 'bani' && bani && <BaniReader bani={bani} preferences={preferences} setPreferences={setPreferences} />}
    {screen === 'browse' && <Browse tab={browseTab} setTab={setBrowseTab} filter={browseFilter} setFilter={setBrowseFilter} banis={banis} contributors={contributors} raags={raags} rankings={rankings} openBani={openBani} openContributor={openContributor} openRaag={openRaag} openWord={openWord} />}
    {screen === 'contributor' && selectedContributor && <Units heading={selectedContributor.name} summary={`${selectedContributor.unitCount.toLocaleString()} Sabads or passages`} units={contributorUnits} openSabad={openSabad} more={moreContributor} hasMore={contributorUnits.length < selectedContributor.unitCount} />}
    {screen === 'raag' && selectedRaag && <RaagView raag={selectedRaag} people={raagContributors} selected={raagContributor} filter={filterRaag} units={raagUnits} openSabad={openSabad} more={moreRaag} />}
    {screen === 'search' && <SearchView query={query} setQuery={setQuery} mode={searchMode} setMode={setSearchMode} run={runSearch} response={search} banis={banis} contributors={contributors} raags={raags} openBani={openBani} openContributor={openContributor} openRaag={openRaag} openSabad={openSabad} openWord={openWord} />}
    {screen === 'word' && <WordView word={selectedWord} stats={wordStats} concordance={concordance} related={relatedForms} grouped={grouped} group={forms => void corpusGateway.groupedFrequency(forms, sourceWorkId).then(setGrouped)} more={moreConcordance} openSabad={openSabad} openGlossary={openGlossary} />}
    {screen === 'glossary' && <GlossaryView word={selectedWord} results={glossary} search={openGlossary} openWord={openWord} />}
    {screen === 'saved' && <Saved personal={personal} openSabad={openSabad} openWord={openWord} />}
    {screen === 'tggsp' && <section><PageHeading eyebrow="Data details" title="The Guru Granth Sahib Project">Only reviewed mappings are attached to a Sabad. Unresolved material remains separate.</PageHeading><div className="metrics"><EmptyMetric label="Analysis sections" value={coverage?.totalLayers ?? null} /><EmptyMetric label="Mapped sections" value={coverage?.mappedLayers ?? null} /><EmptyMetric label="Mapped Sabads" value={coverage?.mappedTextUnits ?? null} /></div></section>}
    {activeLine && <LineSheet line={activeLine} personal={personal} setPersonal={setPersonal} close={() => setActiveLine(null)} openSabad={openSabad} openWord={openWord} />}
  </div></Chrome>;
}

type CommonReader = { preferences: ReaderPreferences; setPreferences: (next: ReaderPreferences | ((p: ReaderPreferences) => ReaderPreferences)) => void; personal: PersonalData; setPersonal: (next: PersonalData | ((p: PersonalData) => PersonalData)) => void; openSabad: (id: string) => Promise<void>; openWord: (word: string) => Promise<void>; setActiveLine: (line: CanonicalLine | null) => void };

function Home({ info, query, setQuery, runSearch, loadAng, showBrowse, continueReading }: { info: CorpusInfo | null; query: string; setQuery: (v: string) => void; runSearch: () => Promise<void>; loadAng: (n: number) => Promise<void>; showBrowse: (tab: BrowseTab) => void; continueReading: () => void }) {
  const [ang, setAng] = useState('1'); return <section><PageHeading eyebrow="Personal reading & understanding" title="Gurbani Reader">Read continuously, find exact forms, and explore by Bani, contributor or Raag.</PageHeading>
    <button className="continue-card" onClick={continueReading}>Continue reading <b>→</b></button><form className="search-row large" onSubmit={e => { e.preventDefault(); void runSearch(); }}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Gurmukhi, naam, English or first letters" /><button>Search</button></form>
    <div className="quick-grid"><button onClick={() => showBrowse('banis')}><b>Banis</b><span>Asa Ki Vaar, Salok Mahalla 9…</span></button><button onClick={() => showBrowse('contributors')}><b>Contributors</b><span>All authors and their Sabads</span></button><button onClick={() => showBrowse('raags')}><b>Raags</b><span>Counts and contributor filters</span></button><button onClick={() => showBrowse('words')}><b>Word frequency</b><span>Complete ranked index</span></button></div>
    <form className="ang-jump" onSubmit={e => { e.preventDefault(); void loadAng(Number(ang)); }}><label>Go directly to Ang <input inputMode="numeric" value={ang} onChange={e => setAng(e.target.value)} /></label><button>Open</button></form><DataFooter info={info} /></section>;
}

function SourcePicker({ sources, value, onChange }: { sources: SourceWorkOption[]; value: string; onChange: (v: string) => void }) { return <label className="source-picker"><span>Text</span><select value={value} onChange={e => onChange(e.target.value)}>{sources.map(s => <option value={s.id} key={s.id}>{s.title}</option>)}</select></label>; }

function AngReader({ ang, maxAng, lines, loadAng, ...props }: { ang: number; maxAng: number; lines: CanonicalLine[]; loadAng: (n: number) => Promise<void> } & CommonReader) { return <section><PageHeading eyebrow="Continuous reading" title={`Ang ${ang}`}>Read without interruptions; tap a line only when you want actions.</PageHeading><TextControls preferences={props.preferences} setPreferences={props.setPreferences} /><div className="pager"><button disabled={ang <= 1} onClick={() => void loadAng(ang - 1)}>← Previous</button><button disabled={ang >= maxAng} onClick={() => void loadAng(ang + 1)}>Next →</button></div><ReaderLines lines={lines} {...props} /></section>; }

function SabadReader({ sabad, ...props }: { sabad: ShabadView } & CommonReader) { return <section><PageHeading eyebrow={`${sabad.contributorName} · ${sabad.raag}`} title="Complete Sabad">Ang {range(sabad.firstAng, sabad.lastAng)}</PageHeading><TextControls preferences={props.preferences} setPreferences={props.setPreferences} /><ReaderLines lines={sabad.lines} {...props} />{props.preferences.showProviderLayers && <ProviderLayers layers={sabad.providerLayers} visibility={props.preferences.providerLayerVisibility} setVisibility={(type, visible) => props.setPreferences(p => ({ ...p, providerLayerVisibility: { ...p.providerLayerVisibility, [type]: visible } }))} scale={props.preferences.interpretationScale} />}</section>; }

function ReaderLines({ lines, preferences, personal, setPersonal, openWord, setActiveLine }: Pick<CommonReader, 'preferences' | 'personal' | 'setPersonal' | 'openWord' | 'setActiveLine'> & { lines: CanonicalLine[] }) { const study = preferences.readerMode === 'study'; return <article className={`reader-flow ${study ? 'study' : 'reading'}`}>{lines.map(line => <div className="reader-line" key={line.id} onClick={() => !study && setActiveLine(line)} style={{ lineHeight: preferences.lineSpacing }}><p className="gurmukhi" style={{ fontSize: `${preferences.textScale}em` }}>{study && preferences.wordMode ? words(line.gurmukhi, openWord) : line.gurmukhi}</p>{preferences.showTransliteration && line.transliteration && <p className="transliteration" style={{ fontSize: `${preferences.transliterationScale}em` }}>{line.transliteration}</p>}{study && <div className="line-tools"><small>Ang {line.ang} · {line.contributorName}</small><button onClick={() => setPersonal(p => ({ ...p, bookmarks: toggleValue(p.bookmarks, line.id) }))}>{personal.bookmarks.includes(line.id) ? 'Bookmarked' : 'Bookmark'}</button><button onClick={() => setActiveLine(line)}>More</button></div>}</div>)}</article>; }

function BaniReader({ bani, preferences, setPreferences }: { bani: BaniView; preferences: ReaderPreferences; setPreferences: CommonReader['setPreferences'] }) { return <section><PageHeading eyebrow="Named Bani" title={<span className="gurmukhi">{bani.gurmukhi}</span>}>{bani.transliteration}</PageHeading><TextControls preferences={preferences} setPreferences={setPreferences} /><article className="reader-flow">{bani.lines.map(line => <div className={line.headerLevel ? 'reader-line bani-heading' : 'reader-line'} key={line.order} style={{ lineHeight: preferences.lineSpacing }}><p className="gurmukhi" style={{ fontSize: `${preferences.textScale}em` }}>{line.gurmukhi}</p>{preferences.showTransliteration && <p className="transliteration" style={{ fontSize: `${preferences.transliterationScale}em` }}>{line.transliteration}</p>}</div>)}</article><p className="attribution-note">Ordered Bani text: {bani.attributionLabel}.</p></section>; }

function Browse(p: { tab: BrowseTab; setTab: (v: BrowseTab) => void; filter: string; setFilter: (v: string) => void; banis: BaniSummary[]; contributors: ContributorSummary[]; raags: RaagSummary[]; rankings: RankedForm[]; openBani: (v: BaniSummary) => Promise<void>; openContributor: (v: ContributorSummary) => Promise<void>; openRaag: (v: RaagSummary) => Promise<void>; openWord: (v: string) => Promise<void> }) { const q = fold(p.filter); return <section><PageHeading eyebrow="Browse" title="Find a path into Gurbani">All available entries are shown; filter within the current section.</PageHeading><div className="tabs">{(['banis','contributors','raags','words'] as BrowseTab[]).map(tab => <button className={p.tab === tab ? 'active' : ''} onClick={() => p.setTab(tab)} key={tab}>{tab === 'banis' ? 'Banis' : title(tab)}</button>)}</div><input className="filter" value={p.filter} onChange={e => p.setFilter(e.target.value)} placeholder={`Filter ${p.tab}`} /><div className="browse-list">
    {p.tab === 'banis' && p.banis.filter(x => fold(`${x.gurmukhi} ${x.transliteration} ${x.token}`).includes(q)).map(x => <button key={x.id} onClick={() => void p.openBani(x)}><span className="gurmukhi">{x.gurmukhi}</span><strong>{x.transliteration}</strong><small>{x.verseCount.toLocaleString()} ordered verses</small></button>)}
    {p.tab === 'contributors' && p.contributors.filter(x => fold(x.name).includes(q)).map(x => <button key={x.id} onClick={() => void p.openContributor(x)}><strong>{x.name}</strong><small>{x.unitCount.toLocaleString()} Sabads or passages</small></button>)}
    {p.tab === 'raags' && p.raags.filter(x => fold(x.name).includes(q)).map(x => <button key={x.id + x.name} onClick={() => void p.openRaag(x)}><strong>{x.name}</strong><small>{x.unitCount.toLocaleString()} Sabads</small></button>)}
    {p.tab === 'words' && p.rankings.filter(x => x.form.includes(p.filter)).map((x, i) => <button key={x.form} onClick={() => void p.openWord(x.form)}><b>{i + 1}</b><span className="gurmukhi">{x.form}</span><strong>{x.frequency.toLocaleString()}</strong><small>occurrences</small></button>)}
  </div></section>; }

function Units({ heading, summary, units, openSabad, more, hasMore }: { heading: string; summary: string; units: TextUnitSummary[]; openSabad: (v: string) => Promise<void>; more: () => Promise<void>; hasMore: boolean }) { return <section><PageHeading eyebrow="Contributor" title={heading}>{summary}</PageHeading><UnitList units={units} openSabad={openSabad} />{hasMore && <button className="load-more" onClick={() => void more()}>Load 50 more</button>}</section>; }
function UnitList({ units, openSabad }: { units: TextUnitSummary[]; openSabad: (v: string) => Promise<void> }) { return <div className="unit-list">{units.map(u => <button key={u.id} onClick={() => void openSabad(u.id)}><small>{u.contributorName} · Ang {range(u.firstAng, u.lastAng)}</small><span className="gurmukhi">{u.preview}</span>{u.transliteration && <span className="transliteration">{u.transliteration}</span>}<b>Read complete Sabad →</b></button>)}</div>; }
function RaagView({ raag, people, selected, filter, units, openSabad, more }: { raag: RaagSummary; people: RaagContributorSummary[]; selected: string; filter: (v: string) => Promise<void>; units: TextUnitSummary[]; openSabad: (v: string) => Promise<void>; more: () => Promise<void> }) { return <section><PageHeading eyebrow="Raag" title={raag.name}>{raag.unitCount.toLocaleString()} Sabads</PageHeading><label className="raag-filter">Contributor within this Raag <select value={selected} onChange={e => void filter(e.target.value)}><option value="">All contributors</option>{people.map(p => <option value={p.id} key={p.id}>{p.name} ({p.unitCount})</option>)}</select></label><UnitList units={units} openSabad={openSabad} /><button className="load-more" onClick={() => void more()}>Load more</button></section>; }

function SearchView(p: { query: string; setQuery: (v: string) => void; mode: SearchMode; setMode: (v: SearchMode) => void; run: () => Promise<void>; response: CorpusSearchResponse; banis: BaniSummary[]; contributors: ContributorSummary[]; raags: RaagSummary[]; openBani: (v: BaniSummary) => Promise<void>; openContributor: (v: ContributorSummary) => Promise<void>; openRaag: (v: RaagSummary) => Promise<void>; openSabad: (v: string) => Promise<void>; openWord: (v: string) => Promise<void> }) { const q = fold(p.query); const baniHits = q ? p.banis.filter(x => fold(`${x.transliteration} ${x.gurmukhi} ${x.token}`).includes(q)).slice(0, 10) : []; const peopleHits = q ? p.contributors.filter(x => fold(x.name).includes(q)).slice(0, 10) : []; const raagHits = q ? p.raags.filter(x => fold(x.name).includes(q)).slice(0, 10) : []; return <section><PageHeading eyebrow="Comprehensive search" title="Search Gurbani">Search Gurmukhi, romanised terms, TGGSP English, Bani, contributor, Raag, or first letters.</PageHeading><form className="search-row large" onSubmit={e => { e.preventDefault(); void p.run(); }}><input value={p.query} onChange={e => p.setQuery(e.target.value)} /><button>Search</button></form><label className="search-mode">Method <select value={p.mode} onChange={e => p.setMode(e.target.value as SearchMode)}><option value="auto">Words, phrases & English</option><option value="first-start">First letters · line starts</option><option value="first-any">First letters · anywhere</option><option value="theme">Themes · experimental</option></select></label>{p.mode === 'theme' && <p className="notice">Experimental: searches only the available English TGGSP analysis, using transparent keyword matches. It is not a complete thematic classification.</p>}
    {(baniHits.length + peopleHits.length + raagHits.length > 0) && <div className="search-entities">{baniHits.map(x => <button onClick={() => void p.openBani(x)} key={x.id}><b>Bani</b> {x.transliteration}</button>)}{peopleHits.map(x => <button onClick={() => void p.openContributor(x)} key={x.id}><b>Contributor</b> {x.name}</button>)}{raagHits.map(x => <button onClick={() => void p.openRaag(x)} key={x.id + x.name}><b>Raag</b> {x.name}</button>)}</div>}
    {p.response.candidateForms.length > 0 && <div className="candidates"><span>Exact forms:</span>{p.response.candidateForms.map(x => <button key={x.gurmukhi} onClick={() => void p.openWord(x.gurmukhi)}><span className="gurmukhi">{x.gurmukhi}</span> <small>{x.note}</small></button>)}</div>}
    <div className="search-results">{p.response.results.map(r => <button key={r.id} onClick={() => r.textUnitId && void p.openSabad(r.textUnitId)}><span className="tag">{r.resultType}</span><strong>{r.title}</strong><small>{r.subtitle}</small><span className="gurmukhi">{r.gurmukhi}</span>{r.transliteration && <span className="transliteration">{r.transliteration}</span>}{r.english && <p>{r.english}</p>}<b>Open complete Sabad →</b></button>)}{p.response.query && !p.response.results.length && <p className="empty">No text matches found. Try another method or spelling.</p>}</div></section>; }

function WordView({ word, stats, concordance, related, grouped, group, more, openSabad, openGlossary }: { word: string; stats: WordStats | null; concordance: ConcordancePage; related: RelatedForm[]; grouped: GroupedFrequency | null; group: (v: string[]) => void; more: () => Promise<void>; openSabad: (v: string) => Promise<void>; openGlossary: (v: string) => Promise<void> }) { const [forms, setForms] = useState([word]); useEffect(() => setForms([word]), [word]); return <section><PageHeading eyebrow="Exact written form" title={<span className="gurmukhi">{word}</span>}>The exact total never silently combines spellings.</PageHeading><div className="metrics"><EmptyMetric label="Occurrences" value={stats?.rawFrequency ?? null} /><EmptyMetric label="Matching passages" value={stats?.distinctLines ?? null} /><EmptyMetric label="Sabads or units" value={stats?.distinctUnits ?? null} /></div><button className="secondary" onClick={() => void openGlossary(word)}>Open glossary</button>{related.length > 0 && <details className="panel"><summary>Optional form grouping</summary>{[word, ...related.map(x => x.form)].map(x => <label className="form-option" key={x}><input type="checkbox" checked={forms.includes(x)} disabled={x === word} onChange={() => setForms(v => v.includes(x) ? v.filter(y => y !== x) : [...v, x])} /><span className="gurmukhi">{x}</span></label>)}<button disabled={forms.length < 2} onClick={() => group(forms)}>Calculate selected forms</button>{grouped && <p><b>{grouped.totalFrequency.toLocaleString()}</b> combined occurrences across the explicitly selected forms.</p>}</details>}<article className="concordance"><h2>Concordance</h2><p>Showing {concordance.matches.length.toLocaleString()} of {concordance.total.toLocaleString()} matching passages.</p>{concordance.matches.map(l => <button key={l.id} onClick={() => void openSabad(l.textUnitId)}><span className="gurmukhi">{l.gurmukhi}</span><small>{l.contributorName} · Ang {l.ang}</small><b>Open complete Sabad →</b></button>)}{concordance.matches.length < concordance.total && <button className="load-more" onClick={() => void more()}>Load 50 more</button>}</article></section>; }
function GlossaryView({ word, results, search, openWord }: { word: string; results: GlossaryResult[]; search: (v: string) => Promise<void>; openWord: (v: string) => Promise<void> }) { const [q, setQ] = useState(word); return <section><PageHeading eyebrow="Contextual glossary" title={<span className="gurmukhi">{word}</span>}>Interpretation remains distinct from exact source-text evidence.</PageHeading><form className="search-row" onSubmit={e => { e.preventDefault(); void search(q); }}><input value={q} onChange={e => setQ(e.target.value)} /><button>Search</button></form><button className="secondary" onClick={() => void openWord(word)}>View exact frequency</button>{results.map(x => <article className="panel" key={x.id}><h2 className="gurmukhi">{x.headword}</h2><p>{plain(x.content)}</p><small>{x.provider}</small></article>)}</section>; }
function Saved({ personal, openSabad, openWord }: { personal: PersonalData; openSabad: (v: string) => Promise<void>; openWord: (v: string) => Promise<void> }) { return <section><PageHeading eyebrow="Personal" title="Saved">Bookmarks and terms remain on this device.</PageHeading>{personal.readingPosition && <button className="continue-card" onClick={() => void openSabad(personal.readingPosition!)}>Continue last Sabad →</button>}<h2>Saved terms</h2>{personal.savedTerms.map(x => <button className="saved-term gurmukhi" onClick={() => void openWord(x)} key={x}>{x}</button>)}</section>; }
function LineSheet({ line, personal, setPersonal, close, openSabad, openWord }: { line: CanonicalLine; personal: PersonalData; setPersonal: CommonReader['setPersonal']; close: () => void; openSabad: (v: string) => Promise<void>; openWord: (v: string) => Promise<void> }) { return <div className="sheet-backdrop" onClick={close}><aside className="line-sheet" onClick={e => e.stopPropagation()}><button className="sheet-close" onClick={close}>Close</button><p className="gurmukhi">{line.gurmukhi}</p><button onClick={() => { setPersonal(p => ({ ...p, bookmarks: toggleValue(p.bookmarks, line.id) })); close(); }}>{personal.bookmarks.includes(line.id) ? 'Remove bookmark' : 'Bookmark line'}</button><button onClick={() => { close(); void openSabad(line.textUnitId); }}>Open complete Sabad</button><button onClick={() => { const first = cleanWord(line.gurmukhi); close(); void openWord(first); }}>Explore first word</button></aside></div>; }

function words(text: string, open: (v: string) => Promise<void>) { return text.split(/(\s+)/u).map((part, i) => /[\p{L}\p{M}]/u.test(part) ? <button className="word" key={i} onClick={e => { e.stopPropagation(); void open(part); }}>{part}</button> : part); }
function cleanWord(value: string) { return value.normalize('NFC').match(/[\p{L}\p{M}]+/u)?.[0] ?? ''; }
function fold(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/gu, '').toLowerCase().trim(); }
function title(value: string) { return value[0].toUpperCase() + value.slice(1); }
function range(a: number, b: number) { return a === b ? String(a) : `${a}–${b}`; }
function plain(value: string) { try { return Object.values(JSON.parse(value) as Record<string, unknown>).filter(x => typeof x === 'string').join(' '); } catch { return value.replace(/<[^>]*>/gu, ' '); } }
