import { useEffect, useState } from 'react';
import type { CSSProperties } from 'react';
import { Chrome } from './components/Chrome';
import { DataFooter, EmptyMetric, PageHeading } from './components/Common';
import { GurmukhiKeyboard } from './components/GurmukhiKeyboard';
import { ProviderLayers } from './components/ProviderLayers';
import { TextControls } from './components/TextControls';
import { exportBackup, parseBackup } from './lib/backup';
import { corpusGateway } from './lib/gateway';
import { useNavigation } from './lib/navigation';
import { defaultPersonalData, defaultPreferences, toggleValue, usePersistentState } from './lib/persistence';
import type { PersonalData, ReaderPreferences, SavedSearch } from './lib/persistence';
import type { BaniSummary, BaniView, CanonicalLine, ConcordancePage, ContributorSummary, CorpusInfo, CorpusSearchResponse, GlossaryResult, GroupedFrequency, ProviderCoverage, RaagContributorSummary, RaagSummary, RankedForm, RelatedForm, SearchFilters, SearchMode, ShabadView, SourceWorkOption, TextUnitSummary, WordStats } from './types';

const emptySearch: CorpusSearchResponse = { query: '', mode: 'latin', results: [], candidateForms: [] };
const emptyConcordance: ConcordancePage = { total: 0, offset: 0, limit: 50, matches: [] };
type BrowseTab = 'banis' | 'contributors' | 'raags' | 'words';
const defaultSearchFilters: SearchFilters = { sourceWorkId: 'all', raag: '', contributorId: '', tggspOnly: false, providerContentTypes: [] };

export default function App() {
  const { screen, navigate, back, exitHint } = useNavigation();
  const [query, setQuery] = useState('naam'); const [searchMode, setSearchMode] = useState<SearchMode>('auto');
  const [searchFilters, setSearchFilters] = useState<SearchFilters>(defaultSearchFilters);
  const [search, setSearch] = useState<CorpusSearchResponse>(emptySearch); const [sources, setSources] = useState<SourceWorkOption[]>([]);
  const [sourceWorkId, setSourceWorkId] = useState('source:G'); const [info, setInfo] = useState<CorpusInfo | null>(null);
  const [ang, setAng] = useState(1); const [angLines, setAngLines] = useState<CanonicalLine[]>([]); const [sabad, setSabad] = useState<ShabadView | null>(null);
  const [rankings, setRankings] = useState<RankedForm[]>([]); const [rankingTotal, setRankingTotal] = useState(0); const [wordLetter, setWordLetter] = useState(''); const [contributors, setContributors] = useState<ContributorSummary[]>([]);
  const [searchContributors, setSearchContributors] = useState<ContributorSummary[]>([]); const [searchRaags, setSearchRaags] = useState<RaagSummary[]>([]);
  const [selectedContributor, setSelectedContributor] = useState<ContributorSummary | null>(null); const [contributorUnits, setContributorUnits] = useState<TextUnitSummary[]>([]);
  const [raags, setRaags] = useState<RaagSummary[]>([]); const [selectedRaag, setSelectedRaag] = useState<RaagSummary | null>(null);
  const [raagContributors, setRaagContributors] = useState<RaagContributorSummary[]>([]); const [raagContributor, setRaagContributor] = useState(''); const [raagUnits, setRaagUnits] = useState<TextUnitSummary[]>([]);
  const [banis, setBanis] = useState<BaniSummary[]>([]); const [bani, setBani] = useState<BaniView | null>(null);
  const [searchBanis, setSearchBanis] = useState<BaniSummary[]>([]);
  const [browseTab, setBrowseTab] = useState<BrowseTab>('banis'); const [browseFilter, setBrowseFilter] = useState('');
  const [selectedWord, setSelectedWord] = useState('ਹਰਿ'); const [wordStats, setWordStats] = useState<WordStats | null>(null);
  const [wordFilters, setWordFilters] = useState<SearchFilters>({ ...defaultSearchFilters, sourceWorkId: 'source:G' });
  const [concordance, setConcordance] = useState<ConcordancePage>(emptyConcordance); const [relatedForms, setRelatedForms] = useState<RelatedForm[]>([]); const [grouped, setGrouped] = useState<GroupedFrequency | null>(null);
  const [glossary, setGlossary] = useState<GlossaryResult[]>([]); const [coverage, setCoverage] = useState<ProviderCoverage | null>(null);
  const [activeLine, setActiveLine] = useState<CanonicalLine | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null); const [savedLines, setSavedLines] = useState<CanonicalLine[]>([]); const [historyUnits, setHistoryUnits] = useState<TextUnitSummary[]>([]);
  const [matchedLineId, setMatchedLineId] = useState<string | null>(null);
  const [preferences, setPreferences] = usePersistentState('gurbani:preferences:v3', defaultPreferences);
  const [personal, setPersonal] = usePersistentState('gurbani:personal:v1', defaultPersonalData);
  const currentSource = sources.find(source => source.id === sourceWorkId);

  useEffect(() => { document.documentElement.dataset.theme = preferences.theme; document.documentElement.style.setProperty('--bg', preferences.backgroundColor); }, [preferences.backgroundColor, preferences.theme]);
  useEffect(() => { void loadSource('source:G', true); }, []);
  useEffect(() => { if (screen !== 'saved') return; const lineIds = [...new Set([...personal.bookmarks, ...Object.keys(personal.notes), ...personal.collections.flatMap(collection => collection.lineIds)])]; const unitIds = [...new Set(personal.history.map(item => item.textUnitId))]; void Promise.all([corpusGateway.linesByIds(lineIds), corpusGateway.textUnitsByIds(unitIds)]).then(([lines, units]) => { setSavedLines(lines); setHistoryUnits(units); }); }, [personal, screen]);

  async function loadSource(source: string, first = false) {
    setBusy(true); setError(null);
    try {
      const [sourceInfo, sourceRows, lines, formPage, people, raagRows, baniRows, providerCoverage, allPeople, allRaagRows, allBaniRows] = await Promise.all([
        corpusGateway.corpusInfo(), corpusGateway.sources(), corpusGateway.getLines(1, source), corpusGateway.rankedFormsPage(source, '', 100, 0),
        corpusGateway.contributorSummaries(1000, source), corpusGateway.raagSummaries(source), corpusGateway.namedBanis(source), corpusGateway.providerCoverage(),
        corpusGateway.contributorSummaries(1000, 'all'), corpusGateway.raagSummaries('all'), corpusGateway.namedBanis('all')
      ]);
      setInfo(sourceInfo); setSources(sourceRows); setSourceWorkId(source); setAng(1); setAngLines(lines); setRankings(formPage.forms); setRankingTotal(formPage.total); setWordLetter('');
      setContributors(people); setRaags(raagRows); setBanis(baniRows); setCoverage(providerCoverage); setSearchContributors(allPeople); setSearchRaags(allRaagRows); setSearchBanis(allBaniRows); setSearch(emptySearch);
      if (!first) navigate('home');
    } catch { setError('The installed reading data could not be opened. Remove the previous app build, then reinstall this one.'); }
    finally { setBusy(false); }
  }

  async function loadAng(value: number) { const next = Math.max(1, Math.min(currentSource?.maxAng ?? 1430, value)); setBusy(true); try { setAng(next); setAngLines(await corpusGateway.getLines(next, sourceWorkId)); navigate('read'); } catch { setError('That Ang could not be opened.'); } finally { setBusy(false); } }
  async function openSabad(id: string, lineId: string | null = null) { setBusy(true); try { const value = await corpusGateway.getTextUnit(id); setSabad(value); setMatchedLineId(lineId); setPersonal(p => ({ ...p, readingPosition: value.id, history: [{ textUnitId: value.id, lineId, visitedAt: new Date().toISOString() }, ...p.history.filter(item => item.textUnitId !== value.id)].slice(0, 100) })); navigate('sabad'); } catch { setError('The complete Sabad could not be opened.'); } finally { setBusy(false); } }
  async function openBani(row: BaniSummary) { setBusy(true); try { setBani(await corpusGateway.getBani(row.id)); navigate('bani'); } catch { setError('This Bani could not be opened.'); } finally { setBusy(false); } }
  async function openContributor(row: ContributorSummary) { const source = row.id === 'contributor:combined:bhai-gurdas' ? 'source:B' : 'source:G'; setBusy(true); setSelectedContributor(row); try { setContributorUnits(await corpusGateway.contributorUnits(row.id, source, 50, 0)); navigate('contributor'); } catch { setError('This contributor’s Sabads could not be opened.'); } finally { setBusy(false); } }
  async function moreContributor() { if (!selectedContributor) return; const source = selectedContributor.id === 'contributor:combined:bhai-gurdas' ? 'source:B' : 'source:G'; const rows = await corpusGateway.contributorUnits(selectedContributor.id, source, 50, contributorUnits.length); setContributorUnits(v => [...v, ...rows]); }
  async function openRaag(row: RaagSummary) { setBusy(true); setSelectedRaag(row); setRaagContributor(''); try { const [people, units] = await Promise.all([corpusGateway.raagContributorSummaries(row.name, sourceWorkId), corpusGateway.raagUnits(row.name, sourceWorkId, 50, 0)]); setRaagContributors(people); setRaagUnits(units); navigate('raag'); } catch { setError('This Raag could not be opened.'); } finally { setBusy(false); } }
  async function filterRaag(contributorId: string) { if (!selectedRaag) return; setRaagContributor(contributorId); setRaagUnits(await corpusGateway.raagUnits(selectedRaag.name, sourceWorkId, 50, 0, contributorId || undefined)); }
  async function moreRaag() { if (!selectedRaag) return; const rows = await corpusGateway.raagUnits(selectedRaag.name, sourceWorkId, 50, raagUnits.length, raagContributor || undefined); setRaagUnits(v => [...v, ...rows]); }
  async function runSearch() { setBusy(true); try { setSearch(await corpusGateway.searchCorpus(query, searchFilters, 100, searchMode)); navigate('search'); } catch { setSearch(emptySearch); setError('Search could not query the installed data.'); navigate('search'); } finally { setBusy(false); } }
  async function restoreSearch(row: SavedSearch) { const filters = { ...defaultSearchFilters, ...row.filters } as SearchFilters; const mode = row.mode === 'theme' ? 'theme' : 'auto'; setQuery(row.query); setSearchFilters(filters); setSearchMode(mode); setBusy(true); try { setSearch(await corpusGateway.searchCorpus(row.query, filters, 100, mode)); navigate('search'); } finally { setBusy(false); } }
  async function openWord(raw: string, filters?: SearchFilters) { const word = cleanWord(raw); if (!word) return; const scope = filters ?? { ...defaultSearchFilters, sourceWorkId }; setBusy(true); setSelectedWord(word); setWordFilters(scope); try { const [stats, page, related] = await Promise.all([corpusGateway.exactWordStats(word, scope), corpusGateway.concordance(word, scope, 50, 0), corpusGateway.relatedForms(word, scope.sourceWorkId, 30)]); setWordStats(stats); setConcordance(page); setRelatedForms(related); setGrouped(null); navigate('word'); } catch { setError('No exact count has been inferred or substituted.'); } finally { setBusy(false); } }
  async function moreConcordance() { const page = await corpusGateway.concordance(selectedWord, wordFilters, 50, concordance.matches.length); setConcordance(v => ({ ...page, offset: 0, matches: [...v.matches, ...page.matches] })); }
  async function openGlossary(word: string) { setSelectedWord(cleanWord(word)); setGlossary(await corpusGateway.glossary(cleanWord(word), 40)); navigate('glossary'); }
  function showBrowse(tab: BrowseTab) { setBrowseTab(tab); setBrowseFilter(''); navigate('browse'); }
  async function loadRankings(letter: string, reset = true) { const offset = reset ? 0 : rankings.length; const page = await corpusGateway.rankedFormsPage(sourceWorkId, letter, 100, offset); setWordLetter(letter); setRankingTotal(page.total); setRankings(current => reset ? page.forms : [...current, ...page.forms]); }
  async function importFile(file: File) { try { const backup = parseBackup(await file.text()); setPersonal({ ...defaultPersonalData, ...backup.personal }); setPreferences({ ...defaultPreferences, ...backup.preferences, providerLayerVisibility: { ...defaultPreferences.providerLayerVisibility, ...backup.preferences.providerLayerVisibility } }); setMessage('Backup imported.'); } catch { setError('That file is not a valid Gurbani Reader backup.'); } }

  const common = { preferences, setPreferences, personal, setPersonal, openSabad, openWord, setActiveLine, matchedLineId };
  return <Chrome active={screen} onNavigate={navigate} onBack={back}><div className="screen" style={{ '--gurmukhi-color': preferences.gurmukhiColor, '--latin-color': preferences.latinColor } as CSSProperties}>
    {busy && <div className="busy">Opening…</div>}{exitHint && <div className="exit-hint">Swipe back again to exit</div>}{message && <div className="success" role="status">{message}<button onClick={() => setMessage(null)}>Dismiss</button></div>}{error && <div className="error" role="alert">{error}<button onClick={() => setError(null)}>Dismiss</button></div>}
    <SourcePicker sources={sources} value={sourceWorkId} onChange={value => void loadSource(value)} />
    {screen === 'home' && <Home info={info} query={query} setQuery={setQuery} runSearch={runSearch} loadAng={loadAng} showBrowse={showBrowse} continueReading={() => personal.readingPosition ? void openSabad(personal.readingPosition) : void loadAng(ang)} />}
    {screen === 'read' && <AngReader ang={ang} maxAng={currentSource?.maxAng ?? 1430} lines={angLines} loadAng={loadAng} {...common} />}
    {screen === 'sabad' && sabad && <SabadReader sabad={sabad} {...common} />}
    {screen === 'bani' && bani && <BaniReader bani={bani} preferences={preferences} setPreferences={setPreferences} />}
    {screen === 'browse' && <Browse tab={browseTab} setTab={setBrowseTab} filter={browseFilter} setFilter={setBrowseFilter} banis={banis} contributors={contributors} raags={raags} rankings={rankings} rankingTotal={rankingTotal} wordLetter={wordLetter} loadRankings={loadRankings} openBani={openBani} openContributor={openContributor} openRaag={openRaag} openWord={openWord} />}
    {screen === 'contributor' && selectedContributor && <Units heading={selectedContributor.name} summary={`${selectedContributor.unitCount.toLocaleString()} Sabads or passages`} units={contributorUnits} openSabad={openSabad} more={moreContributor} hasMore={contributorUnits.length < selectedContributor.unitCount} />}
    {screen === 'raag' && selectedRaag && <RaagView raag={selectedRaag} people={raagContributors} selected={raagContributor} filter={filterRaag} units={raagUnits} openSabad={openSabad} more={moreRaag} />}
    {screen === 'search' && <SearchView query={query} setQuery={setQuery} mode={searchMode} setMode={setSearchMode} filters={searchFilters} setFilters={setSearchFilters} sources={sources} run={runSearch} response={search} banis={searchBanis} contributors={searchContributors} raags={searchRaags} openBani={openBani} openContributor={openContributor} openRaag={openRaag} openSabad={openSabad} openWord={openWord} saveSearch={() => setPersonal(p => ({ ...p, savedSearches: [{ id: crypto.randomUUID(), title: query || 'TGGSP availability', query, filters: searchFilters, mode: searchMode }, ...p.savedSearches].slice(0, 30) }))} />}
    {screen === 'word' && <WordView word={selectedWord} filters={wordFilters} sources={sources} contributors={searchContributors} stats={wordStats} concordance={concordance} related={relatedForms} grouped={grouped} saved={personal.savedTerms.includes(selectedWord)} toggleSaved={() => setPersonal(p => ({ ...p, savedTerms: toggleValue(p.savedTerms, selectedWord) }))} group={forms => void corpusGateway.groupedFrequency(forms, wordFilters).then(setGrouped)} more={moreConcordance} openSabad={openSabad} openGlossary={openGlossary} />}
    {screen === 'glossary' && <GlossaryView word={selectedWord} results={glossary} search={openGlossary} openWord={openWord} />}
    {screen === 'saved' && <Saved personal={personal} setPersonal={setPersonal} preferences={preferences} savedLines={savedLines} historyUnits={historyUnits} openSabad={openSabad} openWord={openWord} restoreSearch={restoreSearch} exportData={() => exportBackup(personal, preferences).then(() => setMessage('Backup ready to save or share.')).catch(() => setError('The backup could not be exported.'))} importData={importFile} />}
    {screen === 'tggsp' && <section><PageHeading eyebrow="Data details" title="The Guru Granth Sahib Project">Only reviewed mappings are attached to a Sabad. Unresolved material remains separate.</PageHeading><div className="metrics"><EmptyMetric label="Analysis sections" value={coverage?.totalLayers ?? null} /><EmptyMetric label="Mapped sections" value={coverage?.mappedLayers ?? null} /><EmptyMetric label="Mapped Sabads" value={coverage?.mappedTextUnits ?? null} /></div></section>}
    {activeLine && <LineSheet line={activeLine} personal={personal} setPersonal={setPersonal} close={() => setActiveLine(null)} openSabad={openSabad} openWord={openWord} notify={setMessage} />}
  </div></Chrome>;
}

type CommonReader = { preferences: ReaderPreferences; setPreferences: (next: ReaderPreferences | ((p: ReaderPreferences) => ReaderPreferences)) => void; personal: PersonalData; setPersonal: (next: PersonalData | ((p: PersonalData) => PersonalData)) => void; openSabad: (id: string, lineId?: string | null) => Promise<void>; openWord: (word: string, filters?: SearchFilters) => Promise<void>; setActiveLine: (line: CanonicalLine | null) => void; matchedLineId: string | null };

function Home({ info, query, setQuery, runSearch, loadAng, showBrowse, continueReading }: { info: CorpusInfo | null; query: string; setQuery: (v: string) => void; runSearch: () => Promise<void>; loadAng: (n: number) => Promise<void>; showBrowse: (tab: BrowseTab) => void; continueReading: () => void }) {
  const [ang, setAng] = useState('1'); return <section><PageHeading eyebrow="Personal reading & understanding" title="Gurbani Reader">Read continuously, find exact forms, and explore by Bani, contributor or Raag.</PageHeading>
    <button className="continue-card" onClick={continueReading}>Continue reading <b>→</b></button><form className="search-row large" onSubmit={e => { e.preventDefault(); void runSearch(); }}><input aria-label="Search Gurbani" value={query} onChange={e => setQuery(e.target.value)} placeholder="Gurmukhi, naam, English or first letters" /><button>Search</button></form>
    <div className="quick-grid"><button onClick={() => showBrowse('banis')}><b>Banis</b><span>Asa Ki Vaar, Salok Mahalla 9…</span></button><button onClick={() => showBrowse('contributors')}><b>Contributors</b><span>All authors and their Sabads</span></button><button onClick={() => showBrowse('raags')}><b>Raags</b><span>Counts and contributor filters</span></button><button onClick={() => showBrowse('words')}><b>Word frequency</b><span>Complete ranked index</span></button></div>
    <form className="ang-jump" onSubmit={e => { e.preventDefault(); void loadAng(Number(ang)); }}><label>Go directly to Ang <input inputMode="numeric" value={ang} onChange={e => setAng(e.target.value)} /></label><button>Open</button></form><DataFooter info={info} /></section>;
}

function SourcePicker({ sources, value, onChange }: { sources: SourceWorkOption[]; value: string; onChange: (v: string) => void }) { return <label className="source-picker"><span>Text</span><select value={value} onChange={e => onChange(e.target.value)}>{sources.map(s => <option value={s.id} key={s.id}>{s.title}</option>)}</select></label>; }

function AngReader({ ang, maxAng, lines, loadAng, ...props }: { ang: number; maxAng: number; lines: CanonicalLine[]; loadAng: (n: number) => Promise<void> } & CommonReader) { return <section><PageHeading eyebrow="Continuous reading" title={`Ang ${ang}`}>Read without interruptions; tap a line only when you want actions.</PageHeading><TextControls preferences={props.preferences} setPreferences={props.setPreferences} /><div className="pager"><button disabled={ang <= 1} onClick={() => void loadAng(ang - 1)}>← Previous</button><button disabled={ang >= maxAng} onClick={() => void loadAng(ang + 1)}>Next →</button></div><ReaderLines lines={lines} {...props} /></section>; }

function SabadReader({ sabad, ...props }: { sabad: ShabadView } & CommonReader) { const analysisId = `analysis-${sabad.id.replaceAll(':', '-')}`; const [copied, setCopied] = useState(false); const copyReference = async () => { await copyText(`${sabad.preview}\n${sabad.contributorName} · ${sabad.raag} · Ang ${range(sabad.firstAng, sabad.lastAng)}\nGurbani Reader Sabad reference: ${sabad.sourceWorkId} / ${sabad.id}`); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }; return <section><PageHeading eyebrow={`${sabad.contributorName} · ${sabad.raag}`} title="Complete Sabad">Ang {range(sabad.firstAng, sabad.lastAng)}</PageHeading><button className="secondary reference-button" onClick={() => void copyReference()}>{copied ? 'Reference copied' : 'Copy Sabad reference'}</button><TextControls preferences={props.preferences} setPreferences={props.setPreferences} />{sabad.providerLayers.length > 0 ? <button className="analysis-available" onClick={() => document.getElementById(analysisId)?.scrollIntoView({ behavior: 'smooth' })}><b>TGGSP analysis available</b><span>{new Set(sabad.providerLayers.map(layer => layer.contentType)).size} sections · view after the complete Gurmukhi</span></button> : <p className="analysis-unavailable">TGGSP analysis is not available for this Sabad.</p>}<ReaderLines lines={sabad.lines} {...props} />{props.preferences.showProviderLayers && <div id={analysisId}><ProviderLayers layers={sabad.providerLayers} visibility={props.preferences.providerLayerVisibility} setVisibility={(type, visible) => props.setPreferences(p => ({ ...p, providerLayerVisibility: { ...p.providerLayerVisibility, [type]: visible } }))} scale={props.preferences.interpretationScale} /></div>}</section>; }

function ReaderLines({ lines, preferences, personal, setPersonal, openWord, setActiveLine, matchedLineId }: Pick<CommonReader, 'preferences' | 'personal' | 'setPersonal' | 'openWord' | 'setActiveLine' | 'matchedLineId'> & { lines: CanonicalLine[] }) { const study = preferences.readerMode === 'study'; useEffect(() => { if (!matchedLineId) return; window.setTimeout(() => document.getElementById(`line-${safeId(matchedLineId)}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }), 80); }, [matchedLineId, lines]); return <article className={`reader-flow ${study ? 'study' : 'reading'}`}>{lines.map(line => <div id={`line-${safeId(line.id)}`} className={`reader-line ${line.id === matchedLineId ? 'matched-line' : ''}`} key={line.id} onClick={() => !study && setActiveLine(line)} style={{ lineHeight: preferences.lineSpacing }}><p className="gurmukhi" style={{ fontSize: `${preferences.textScale}em` }}>{study && preferences.wordMode ? words(line.gurmukhi, openWord) : line.gurmukhi}</p>{preferences.showTransliteration && line.transliteration && <p className="transliteration" style={{ fontSize: `${preferences.transliterationScale}em` }}>{line.transliteration}</p>}{study && <div className="line-tools"><small>Ang {line.ang} · {line.contributorName}</small><button onClick={() => setPersonal(p => ({ ...p, bookmarks: toggleValue(p.bookmarks, line.id) }))}>{personal.bookmarks.includes(line.id) ? 'Bookmarked' : 'Bookmark'}</button><button onClick={() => setActiveLine(line)}>More</button></div>}</div>)}</article>; }

function BaniReader({ bani, preferences, setPreferences }: { bani: BaniView; preferences: ReaderPreferences; setPreferences: CommonReader['setPreferences'] }) { return <section><PageHeading eyebrow="Named Bani" title={<span className="gurmukhi">{bani.gurmukhi}</span>}>{bani.transliteration}</PageHeading><TextControls preferences={preferences} setPreferences={setPreferences} /><article className="reader-flow">{bani.lines.map(line => <div className={line.headerLevel ? 'reader-line bani-heading' : 'reader-line'} key={line.order} style={{ lineHeight: preferences.lineSpacing }}><p className="gurmukhi" style={{ fontSize: `${preferences.textScale}em` }}>{line.gurmukhi}</p>{preferences.showTransliteration && <p className="transliteration" style={{ fontSize: `${preferences.transliterationScale}em` }}>{line.transliteration}</p>}</div>)}</article><p className="attribution-note">Ordered Bani text: {bani.attributionLabel}.</p></section>; }

function Browse(p: { tab: BrowseTab; setTab: (v: BrowseTab) => void; filter: string; setFilter: (v: string) => void; banis: BaniSummary[]; contributors: ContributorSummary[]; raags: RaagSummary[]; rankings: RankedForm[]; rankingTotal: number; wordLetter: string; loadRankings: (letter: string, reset?: boolean) => Promise<void>; openBani: (v: BaniSummary) => Promise<void>; openContributor: (v: ContributorSummary) => Promise<void>; openRaag: (v: RaagSummary) => Promise<void>; openWord: (v: string) => Promise<void> }) {
  const [baniCategory, setBaniCategory] = useState('all'); const [contributorType, setContributorType] = useState('all'); const [sortOrder, setSortOrder] = useState<'name'|'count'>('name'); const q = fold(p.filter);
  const baniRows = p.banis.filter(x => fold(`${x.gurmukhi} ${x.transliteration} ${x.token}`).includes(q)).filter(x => baniCategory === 'all' || baniGroup(x) === baniCategory);
  const contributorRows = p.contributors.filter(x => fold(x.name).includes(q)).filter(x => contributorType === 'all' || contributorGroup(x.type) === contributorType).sort((a, b) => sortOrder === 'count' ? b.unitCount - a.unitCount : a.name.localeCompare(b.name));
  return <section><PageHeading eyebrow="Browse" title="Find a path into Gurbani">Choose a composition, contributor, Raag or exact written form.</PageHeading><div className="tabs">{(['banis','contributors','raags','words'] as BrowseTab[]).map(tab => <button className={p.tab === tab ? 'active' : ''} onClick={() => p.setTab(tab)} key={tab}>{tab === 'banis' ? 'Banis' : title(tab)}</button>)}</div>
    <div className="browse-tools">{p.tab !== 'words' ? <input aria-label={`Filter ${p.tab}`} className="filter" value={p.filter} onChange={e => p.setFilter(e.target.value)} placeholder={`Filter ${p.tab}`} /> : <p className="result-count">Browse by initial letter below; use Search to find a full exact form.</p>}
      {p.tab === 'banis' && <select value={baniCategory} onChange={e => setBaniCategory(e.target.value)}><option value="all">All Banis</option><option value="nitnem">Nitnem · available here</option><option value="vaaran">Vaaran</option><option value="raag">Raag collections</option><option value="composition">Other compositions</option></select>}
      {p.tab === 'contributors' && <><select value={contributorType} onChange={e => setContributorType(e.target.value)}><option value="all">All contributor types</option><option value="guru">Gurus</option><option value="bhagat">Bhagats</option><option value="bhatt">Bhatts</option><option value="other">Other contributors</option></select><select value={sortOrder} onChange={e => setSortOrder(e.target.value as 'name'|'count')}><option value="name">A–Z</option><option value="count">Most Sabads</option></select></>}
    </div>
    {p.tab === 'words' && <><div className="letter-filter"><button className={!p.wordLetter ? 'active' : ''} onClick={() => void p.loadRankings('')}>All</button>{gurmukhiLetters.map(letter => <button className={p.wordLetter === letter ? 'active gurmukhi' : 'gurmukhi'} onClick={() => void p.loadRankings(letter)} key={letter}>{letter}</button>)}</div><p className="result-count">Showing {p.rankings.length.toLocaleString()} of {p.rankingTotal.toLocaleString()} exact written forms{p.wordLetter && <> beginning <span className="gurmukhi">{p.wordLetter}</span></>}.</p></>}
    <div className={`browse-list ${p.tab === 'words' ? 'compact-words' : ''}`}>
      {p.tab === 'banis' && baniRows.map(x => <button key={x.id} onClick={() => void p.openBani(x)}><span className="gurmukhi">{x.gurmukhi}</span><strong>{x.transliteration}</strong><small>{x.verseCount.toLocaleString()} ordered verses · {baniGroupLabel(baniGroup(x))}</small></button>)}
      {p.tab === 'contributors' && contributorRows.map(x => <button key={x.id} onClick={() => void p.openContributor(x)}><strong>{x.name}</strong><small>{x.unitCount.toLocaleString()} Sabads or passages · {contributorGroup(x.type)}</small></button>)}
      {p.tab === 'raags' && p.raags.filter(x => fold(x.name).includes(q)).map(x => <button key={x.id + x.name} onClick={() => void p.openRaag(x)}><strong>{x.name}</strong><small>{x.unitCount.toLocaleString()} Sabads</small></button>)}
      {p.tab === 'words' && p.rankings.map((x, i) => <button key={x.form} onClick={() => void p.openWord(x.form)}><b>{i + 1}</b><span className="gurmukhi">{x.form}</span><span><strong>{x.frequency.toLocaleString()}</strong> occurrences</span></button>)}
    </div>{p.tab === 'words' && p.rankings.length < p.rankingTotal && <button className="load-more" onClick={() => void p.loadRankings(p.wordLetter, false)}>Load 100 more</button>}
  </section>;
}

function Units({ heading, summary, units, openSabad, more, hasMore }: { heading: string; summary: string; units: TextUnitSummary[]; openSabad: (v: string) => Promise<void>; more: () => Promise<void>; hasMore: boolean }) { return <section><PageHeading eyebrow="Contributor" title={heading}>{summary}</PageHeading><UnitList units={units} openSabad={openSabad} />{hasMore && <button className="load-more" onClick={() => void more()}>Load 50 more</button>}</section>; }
function UnitList({ units, openSabad }: { units: TextUnitSummary[]; openSabad: (v: string) => Promise<void> }) { return <div className="unit-list">{units.map(u => <button key={u.id} onClick={() => void openSabad(u.id)}><small>{u.contributorName} · Ang {range(u.firstAng, u.lastAng)}</small><span className="gurmukhi">{u.preview}</span>{u.transliteration && <span className="transliteration">{u.transliteration}</span>}<b>Read complete Sabad →</b></button>)}</div>; }
function RaagView({ raag, people, selected, filter, units, openSabad, more }: { raag: RaagSummary; people: RaagContributorSummary[]; selected: string; filter: (v: string) => Promise<void>; units: TextUnitSummary[]; openSabad: (v: string) => Promise<void>; more: () => Promise<void> }) { return <section><PageHeading eyebrow="Raag" title={raag.name}>{raag.unitCount.toLocaleString()} Sabads</PageHeading><label className="raag-filter">Contributor within this Raag <select value={selected} onChange={e => void filter(e.target.value)}><option value="">All contributors</option>{people.map(p => <option value={p.id} key={p.id}>{p.name} ({p.unitCount})</option>)}</select></label><UnitList units={units} openSabad={openSabad} /><button className="load-more" onClick={() => void more()}>Load more</button></section>; }

function SearchView(p: { query: string; setQuery: (v: string) => void; mode: SearchMode; setMode: (v: SearchMode) => void; filters: SearchFilters; setFilters: (v: SearchFilters) => void; sources: SourceWorkOption[]; run: () => Promise<void>; response: CorpusSearchResponse; banis: BaniSummary[]; contributors: ContributorSummary[]; raags: RaagSummary[]; openBani: (v: BaniSummary) => Promise<void>; openContributor: (v: ContributorSummary) => Promise<void>; openRaag: (v: RaagSummary) => Promise<void>; openSabad: (v: string, lineId?: string | null) => Promise<void>; openWord: (v: string, filters?: SearchFilters) => Promise<void>; saveSearch: () => void }) {
  const [keyboard, setKeyboard] = useState(false); const q = fold(p.query);
  const baniHits = q ? p.banis.filter(x => fold(`${x.transliteration} ${x.gurmukhi} ${x.token}`).includes(q)).slice(0, 10) : [];
  const peopleHits = q ? p.contributors.filter(x => fold(x.name).includes(q)).slice(0, 10) : [];
  const raagHits = q ? p.raags.filter(x => fold(x.name).includes(q)).slice(0, 10) : [];
  const update = <K extends keyof SearchFilters>(key: K, value: SearchFilters[K]) => p.setFilters({ ...p.filters, [key]: value });
  const activeScope = [p.filters.sourceWorkId === 'all' ? 'All texts' : p.sources.find(x => x.id === p.filters.sourceWorkId)?.title,
    p.filters.raag && `Raag ${p.filters.raag}`, p.filters.contributorId && p.contributors.find(x => x.id === p.filters.contributorId)?.name,
    p.filters.tggspOnly && 'TGGSP available'].filter(Boolean);
  return <section><PageHeading eyebrow="Universal search" title="Search Gurbani">One search checks words, phrases, roman spellings, English analysis and Gurmukhi first-letter sequences.</PageHeading>
    <form className="search-row large" onSubmit={event => { event.preventDefault(); void p.run(); }}><input aria-label="Search Gurbani" value={p.query} onChange={event => p.setQuery(event.target.value)} placeholder="Gurmukhi, naam, English or first letters" /><button type="button" aria-label="Open Gurmukhi keyboard" className="keyboard-button" onClick={() => setKeyboard(value => !value)}>ਕ</button><button>Search</button></form>
    {keyboard && <GurmukhiKeyboard value={p.query} onChange={p.setQuery} close={() => setKeyboard(false)} />}
    <div className="scope-chips">{activeScope.map(item => <span key={String(item)}>{item}</span>)}<button className="save-scope" onClick={p.saveSearch}>Save this search</button></div>
    <details className="search-filters"><summary>Filters</summary><div className="filter-grid">
      <label>Text<select value={p.filters.sourceWorkId} onChange={event => update('sourceWorkId', event.target.value)}><option value="all">All available texts</option>{p.sources.map(source => <option value={source.id} key={source.id}>{source.title}</option>)}</select></label>
      <label>Raag<select value={p.filters.raag} onChange={event => update('raag', event.target.value)}><option value="">All Raags</option>{p.raags.map(raag => <option key={raag.id + raag.name} value={raag.name}>{raag.name} ({raag.unitCount})</option>)}</select></label>
      <label>Contributor<select value={p.filters.contributorId} onChange={event => update('contributorId', event.target.value)}><option value="">All contributors</option>{p.contributors.map(person => <option key={person.id} value={person.id}>{person.name} ({person.unitCount})</option>)}</select></label>
      <label className="toggle"><input type="checkbox" checked={p.filters.tggspOnly} onChange={event => update('tggspOnly', event.target.checked)} /> TGGSP analysis available only</label>
      {p.filters.tggspOnly && <fieldset className="provider-filter"><legend>Required TGGSP section</legend>{providerFilterOptions.map(option => <label key={option.id}><input type="checkbox" checked={p.filters.providerContentTypes.includes(option.id)} onChange={() => update('providerContentTypes', toggleValue(p.filters.providerContentTypes, option.id))} />{option.label}</label>)}</fieldset>}
      <label>Method<select value={p.mode} onChange={event => p.setMode(event.target.value as SearchMode)}><option value="auto">Text, first letters & analysis</option><option value="theme">Themes · experimental</option></select></label>
      <button type="button" className="secondary" onClick={() => { p.setFilters(defaultSearchFilters); p.setMode('auto'); }}>Clear filters</button>
    </div></details>
    {p.mode === 'theme' && <p className="notice">Experimental: keyword matches in available English TGGSP analysis only; this is not a complete thematic classification.</p>}
    {(baniHits.length + peopleHits.length + raagHits.length > 0) && <section className="entity-section"><h2>Related paths</h2><div className="search-entities">{baniHits.map(x => <button onClick={() => void p.openBani(x)} key={x.id}><b>Bani</b> {x.transliteration}</button>)}{peopleHits.map(x => <button onClick={() => void p.openContributor(x)} key={x.id}><b>Contributor</b> {x.name}</button>)}{raagHits.map(x => <button onClick={() => void p.openRaag(x)} key={x.id + x.name}><b>Raag</b> {x.name}</button>)}</div></section>}
    {p.response.candidateForms.length > 0 && <section><h2>Exact forms in this scope</h2><div className="candidates">{p.response.candidateForms.map(x => <button key={x.gurmukhi} onClick={() => void p.openWord(x.gurmukhi, p.filters)}><span className="gurmukhi">{x.gurmukhi}</span> <small>{x.note}</small></button>)}</div></section>}
    <section><h2>Text and analysis matches</h2><div className="search-results">{p.response.results.map(result => <button key={result.id} onClick={() => result.textUnitId && void p.openSabad(result.textUnitId, result.lineId)}><span className="result-badges"><span className="tag">{result.matchKind.replace('-', ' ')}</span>{result.providerContentTypes?.length ? <span className="tggsp-badge">TGGSP</span> : null}</span><strong>{result.title}</strong><small>{result.subtitle}</small><span className="gurmukhi">{result.gurmukhi}</span>{result.transliteration && <span className="transliteration">{result.transliteration}</span>}{result.english && <p>{result.english}</p>}<b>Open at matching line →</b></button>)}{p.response.query && !p.response.results.length && <p className="empty">No text matches in this scope. Clear a filter, try a related exact form, or use the Gurmukhi keyboard.</p>}</div></section>
  </section>;
}

function WordView({ word, filters, sources, contributors, stats, concordance, related, grouped, saved, toggleSaved, group, more, openSabad, openGlossary }: { word: string; filters: SearchFilters; sources: SourceWorkOption[]; contributors: ContributorSummary[]; stats: WordStats | null; concordance: ConcordancePage; related: RelatedForm[]; grouped: GroupedFrequency | null; saved: boolean; toggleSaved: () => void; group: (v: string[]) => void; more: () => Promise<void>; openSabad: (v: string, lineId?: string | null) => Promise<void>; openGlossary: (v: string) => Promise<void> }) { const [forms, setForms] = useState([word]); useEffect(() => setForms([word]), [word]); const scope = [filters.sourceWorkId === 'all' ? 'All texts' : sources.find(x => x.id === filters.sourceWorkId)?.title, filters.raag && `Raag ${filters.raag}`, filters.contributorId && contributors.find(x => x.id === filters.contributorId)?.name, filters.tggspOnly && 'TGGSP available'].filter(Boolean); return <section><PageHeading eyebrow="Exact written form" title={<span className="gurmukhi">{word}</span>}>The exact total never silently combines spellings.</PageHeading><div className="scope-chips">{scope.map(x => <span key={String(x)}>{x}</span>)}</div><div className="metrics"><EmptyMetric label="Occurrences" value={stats?.rawFrequency ?? null} /><EmptyMetric label="Matching passages" value={stats?.distinctLines ?? null} /><EmptyMetric label="Sabads or units" value={stats?.distinctUnits ?? null} /></div><button className="secondary" onClick={toggleSaved}>{saved ? 'Remove saved term' : 'Save exact term'}</button> <button className="secondary" onClick={() => void openGlossary(word)}>Open glossary</button>{related.length > 0 && <details className="panel"><summary>Optional form grouping</summary>{[word, ...related.map(x => x.form)].map(x => <label className="form-option" key={x}><input type="checkbox" checked={forms.includes(x)} disabled={x === word} onChange={() => setForms(v => v.includes(x) ? v.filter(y => y !== x) : [...v, x])} /><span className="gurmukhi">{x}</span></label>)}<button disabled={forms.length < 2} onClick={() => group(forms)}>Calculate selected forms in this scope</button>{grouped && <p><b>{grouped.totalFrequency.toLocaleString()}</b> combined occurrences across the explicitly selected forms.</p>}</details>}<article className="concordance"><h2>Concordance</h2><p>Showing {concordance.matches.length.toLocaleString()} of {concordance.total.toLocaleString()} matching passages in this scope.</p>{concordance.matches.map(l => <button key={l.id} onClick={() => void openSabad(l.textUnitId, l.id)}><span className="gurmukhi">{l.gurmukhi}</span><small>{l.contributorName} · Ang {l.ang}</small><b>Open at matching line →</b></button>)}{concordance.matches.length < concordance.total && <button className="load-more" onClick={() => void more()}>Load 50 more</button>}</article></section>; }
function GlossaryView({ word, results, search, openWord }: { word: string; results: GlossaryResult[]; search: (v: string) => Promise<void>; openWord: (v: string) => Promise<void> }) { const [q, setQ] = useState(word); return <section><PageHeading eyebrow="Contextual glossary" title={<span className="gurmukhi">{word}</span>}>Interpretation remains distinct from exact source-text evidence.</PageHeading><form className="search-row" onSubmit={e => { e.preventDefault(); void search(q); }}><input value={q} onChange={e => setQ(e.target.value)} /><button>Search</button></form><button className="secondary" onClick={() => void openWord(word)}>View exact frequency</button>{results.map(x => <article className="panel" key={x.id}><h2 className="gurmukhi">{x.headword}</h2><p>{plain(x.content)}</p><small>{x.provider}</small></article>)}</section>; }
function Saved({ personal, setPersonal, preferences, savedLines, historyUnits, openSabad, openWord, restoreSearch, exportData, importData }: { personal: PersonalData; setPersonal: CommonReader['setPersonal']; preferences: ReaderPreferences; savedLines: CanonicalLine[]; historyUnits: TextUnitSummary[]; openSabad: (v: string, lineId?: string | null) => Promise<void>; openWord: (v: string) => Promise<void>; restoreSearch: (v: SavedSearch) => Promise<void>; exportData: () => Promise<void>; importData: (file: File) => Promise<void> }) {
  const [tab, setTab] = useState<'bookmarks'|'notes'|'collections'|'history'|'settings'>('bookmarks'); const [collectionName, setCollectionName] = useState(''); const lineMap = new Map(savedLines.map(line => [line.id, line])); const unitMap = new Map(historyUnits.map(unit => [unit.id, unit]));
  const createCollection = () => { const title = collectionName.trim(); if (!title) return; setPersonal(p => ({ ...p, collections: [...p.collections, { id: crypto.randomUUID(), title, lineIds: [], createdAt: new Date().toISOString() }] })); setCollectionName(''); };
  return <section><PageHeading eyebrow="Personal" title="Saved & private">Bookmarks, notes, collections, history and preferences stay under your control.</PageHeading>{personal.readingPosition && <button className="continue-card" onClick={() => void openSabad(personal.readingPosition!)}>Continue last Sabad →</button>}
    <div className="tabs saved-tabs">{(['bookmarks','notes','collections','history','settings'] as const).map(value => <button className={tab === value ? 'active' : ''} onClick={() => setTab(value)} key={value}>{title(value)}</button>)}</div>
    {tab === 'bookmarks' && <SavedLines ids={personal.bookmarks} lineMap={lineMap} empty="No bookmarks yet. Tap a line while reading to add one." openSabad={openSabad} />}
    {tab === 'notes' && <div className="saved-list">{Object.entries(personal.notes).flatMap(([id, note]) => { const line = lineMap.get(id); return line ? [<button key={id} onClick={() => void openSabad(line.textUnitId, line.id)}><span className="gurmukhi">{line.gurmukhi}</span><p>{note}</p><small>Ang {line.ang} · open at line</small></button>] : []; })}{!Object.keys(personal.notes).length && <p className="empty">No notes yet.</p>}</div>}
    {tab === 'collections' && <><div className="new-collection"><input value={collectionName} onChange={e => setCollectionName(e.target.value)} placeholder="New collection name" /><button onClick={createCollection}>Create</button></div>{personal.collections.map(collection => <details className="collection" key={collection.id} open><summary><b>{collection.title}</b> · {collection.lineIds.length} items</summary><SavedLines ids={collection.lineIds} lineMap={lineMap} empty="Add lines from the reading actions." openSabad={openSabad} /><button className="danger-link" onClick={() => setPersonal(p => ({ ...p, collections: p.collections.filter(x => x.id !== collection.id) }))}>Delete collection</button></details>)}</>}
    {tab === 'history' && <div className="saved-list">{personal.history.map(item => { const unit = unitMap.get(item.textUnitId); return unit ? <button key={item.textUnitId} onClick={() => void openSabad(item.textUnitId, item.lineId)}><span className="gurmukhi">{unit.preview}</span><small>{unit.contributorName} · Ang {range(unit.firstAng, unit.lastAng)} · {new Date(item.visitedAt).toLocaleDateString()}</small></button> : null; })}{!personal.history.length && <p className="empty">Reading history will appear here.</p>}</div>}
    {tab === 'settings' && <div className="settings-stack"><section className="panel"><h2>Saved terms</h2>{personal.savedTerms.map(x => <button className="saved-term gurmukhi" onClick={() => void openWord(x)} key={x}>{x}</button>)}</section><section className="panel"><h2>Saved searches</h2>{personal.savedSearches.map(row => <button className="saved-search" onClick={() => void restoreSearch(row)} key={row.id}>{row.title}<small>{row.mode} · reopen with filters</small></button>)}</section><section className="panel"><h2>Backup & restore</h2><p>Export bookmarks, notes, collections, history, saved searches and all reading preferences.</p><button onClick={() => void exportData()}>Export backup</button><label className="import-button">Import backup<input type="file" accept="application/json,.json" onChange={e => { const file = e.target.files?.[0]; if (file) void importData(file); e.currentTarget.value = ''; }} /></label><small>Import replaces current personal data and preferences after validating the backup.</small></section><small>Current theme: {preferences.theme}</small></div>}
  </section>;
}

function SavedLines({ ids, lineMap, empty, openSabad }: { ids: string[]; lineMap: Map<string, CanonicalLine>; empty: string; openSabad: (v: string, lineId?: string | null) => Promise<void> }) { return <div className="saved-list">{ids.flatMap(id => { const line = lineMap.get(id); return line ? [<button key={id} onClick={() => void openSabad(line.textUnitId, line.id)}><span className="gurmukhi">{line.gurmukhi}</span><small>{line.contributorName} · Ang {line.ang} · open at line</small></button>] : []; })}{!ids.length && <p className="empty">{empty}</p>}</div>; }

function LineSheet({ line, personal, setPersonal, close, openSabad, openWord, notify }: { line: CanonicalLine; personal: PersonalData; setPersonal: CommonReader['setPersonal']; close: () => void; openSabad: (v: string, lineId?: string | null) => Promise<void>; openWord: (v: string) => Promise<void>; notify: (v: string) => void }) {
  const [note, setNote] = useState(personal.notes[line.id] ?? ''); const [collectionId, setCollectionId] = useState(personal.collections[0]?.id ?? ''); const [newCollection, setNewCollection] = useState('');
  const saveNote = () => { setPersonal(p => { const notes = { ...p.notes }; if (note.trim()) notes[line.id] = note.trim(); else delete notes[line.id]; return { ...p, notes }; }); notify(note.trim() ? 'Note saved.' : 'Note removed.'); };
  const addToCollection = () => { let id = collectionId; setPersonal(p => { let collections = p.collections; if (newCollection.trim()) { id = crypto.randomUUID(); collections = [...collections, { id, title: newCollection.trim(), lineIds: [], createdAt: new Date().toISOString() }]; } if (!id) return p; return { ...p, collections: collections.map(collection => collection.id === id ? { ...collection, lineIds: [...new Set([...collection.lineIds, line.id])] } : collection) }; }); setNewCollection(''); notify('Added to collection.'); };
  const copyReference = async () => { const ref = `${line.gurmukhi}\n${line.contributorName ?? 'Contributor'} · Ang ${line.ang}\nGurbani Reader reference: ${line.sourceWorkId} / ${line.textUnitId} / ${line.id}`; await copyText(ref); notify('Reference copied.'); };
  return <div className="sheet-backdrop" onClick={close}><aside className="line-sheet" onClick={e => e.stopPropagation()}><button className="sheet-close" onClick={close}>Close</button><p className="gurmukhi">{line.gurmukhi}</p><small>{line.contributorName} · Ang {line.ang}</small><button onClick={() => setPersonal(p => ({ ...p, bookmarks: toggleValue(p.bookmarks, line.id) }))}>{personal.bookmarks.includes(line.id) ? 'Remove bookmark' : 'Bookmark line'}</button><label className="note-editor">Private note<textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Add your note…" /></label><button onClick={saveNote}>Save note</button><div className="collection-adder"><select value={collectionId} onChange={e => setCollectionId(e.target.value)}><option value="">Choose collection</option>{personal.collections.map(collection => <option key={collection.id} value={collection.id}>{collection.title}</option>)}</select><input value={newCollection} onChange={e => setNewCollection(e.target.value)} placeholder="or new collection" /><button onClick={addToCollection} disabled={!collectionId && !newCollection.trim()}>Add</button></div><button onClick={() => { close(); void openSabad(line.textUnitId, line.id); }}>{line.providerLayers?.length ? `Open Sabad · TGGSP available (${line.providerLayers.length})` : 'Open complete Sabad'}</button><button onClick={() => { const first = cleanWord(line.gurmukhi); close(); void openWord(first); }}>Explore first word</button><button className="secondary" onClick={() => void copyReference()}>Copy direct reference</button></aside></div>;
}

function words(text: string, open: (v: string) => Promise<void>) { return text.split(/(\s+)/u).map((part, i) => /[\p{L}\p{M}]/u.test(part) ? <button className="word" key={i} onClick={e => { e.stopPropagation(); void open(part); }}>{part}</button> : part); }
function cleanWord(value: string) { return value.normalize('NFC').match(/[\p{L}\p{M}]+/u)?.[0] ?? ''; }
function fold(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/gu, '').toLowerCase().trim(); }
function title(value: string) { return value[0].toUpperCase() + value.slice(1); }
function range(a: number, b: number) { return a === b ? String(a) : `${a}–${b}`; }
function safeId(value: string) { return value.replace(/[^a-zA-Z0-9_-]/gu, '-'); }
async function copyText(value: string) { try { await navigator.clipboard.writeText(value); } catch { const area = document.createElement('textarea'); area.value = value; area.style.position = 'fixed'; area.style.opacity = '0'; document.body.append(area); area.select(); document.execCommand('copy'); area.remove(); } }
function plain(value: string) { try { return Object.values(JSON.parse(value) as Record<string, unknown>).filter(x => typeof x === 'string').join(' '); } catch { return value.replace(/<[^>]*>/gu, ' '); } }
function baniGroup(row: BaniSummary) { if (['japji','anand'].includes(row.token)) return 'nitnem'; if (row.token.includes('vaar') || row.token.includes('var')) return 'vaaran'; if (fold(row.transliteration).startsWith('raag ')) return 'raag'; return 'composition'; }
function baniGroupLabel(group: string) { return ({ nitnem: 'Nitnem', vaaran: 'Vaaran', raag: 'Raag collection', composition: 'Composition' } as Record<string, string>)[group] ?? group; }
function contributorGroup(type: string) { const value = fold(type); if (value.includes('guru')) return 'guru'; if (value.includes('bhagat')) return 'bhagat'; if (value.includes('bhatt')) return 'bhatt'; return 'other'; }

const gurmukhiLetters = ['ੳ','ਅ','ੲ','ਸ','ਹ','ਕ','ਖ','ਗ','ਘ','ਙ','ਚ','ਛ','ਜ','ਝ','ਞ','ਟ','ਠ','ਡ','ਢ','ਣ','ਤ','ਥ','ਦ','ਧ','ਨ','ਪ','ਫ','ਬ','ਭ','ਮ','ਯ','ਰ','ਲ','ਵ','ੜ','ਸ਼','ਖ਼','ਗ਼','ਜ਼','ਫ਼'];

const providerFilterOptions = [
  { id: 'reference_gurmukhi', label: 'Reference Gurmukhi' }, { id: 'transliteration', label: 'Transcription' },
  { id: 'literal_translation_en', label: 'Literal · English' }, { id: 'literal_translation_pa', label: 'Literal · Panjabi' },
  { id: 'interpretive_transcreation_en', label: 'Transcreation · English' }, { id: 'interpretive_transcreation_pa', label: 'Transcreation · Panjabi' },
  { id: 'commentary_en', label: 'Commentary · English' }, { id: 'commentary_pa', label: 'Commentary · Panjabi' },
  { id: 'poetical_dimension_en', label: 'Poetical dimension · English' }, { id: 'poetical_dimension_pa', label: 'Poetical dimension · Panjabi' }
];
